# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

# This is an example script to demonstrate out-of-box execution of the component.
# Appropriate security measures with respect to key-store management and 
# configuration management should be considered while production deployment.
version: "2.4"

services:

  manufacturer:
    build:
      context: .
      dockerfile: Dockerfile-manufacturer
      # Uncomment and edit proxy configuration if your environment requires proxies.
      # args:
        # http_proxy: http://yourProxy.yourCompany.com:80
        # https_proxy: http://yourProxy.yourCompany.com:443
    image: manufacturer:1.9-SNAPSHOT
    container_name: manufacturer
    restart: on-failure:5
    ports:
      # If different port needs to be used for the manufacturer, modify it here.
      - "8039:8080"
    expose:
      - "8039"
    volumes:
      - ./keys:/keys:ro
    env_file:
      - ./manufacturer.env
    depends_on:
      manufacturer-mariadb:
        condition: service_healthy
    mem_limit: 500m
    mem_reservation: 200m
    cpu_shares: 5
    pids_limit: 100
    networks:
      - manufacturer_network

  manufacturer-mariadb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
      # Uncomment and edit proxy configuration if your environment requires proxies.
      # args:
        # http_proxy: http://yourProxy.yourCompany.com:80
        # https_proxy: http://yourProxy.yourCompany.com:443
    image: manufacturer-mariadb:1.9-SNAPSHOT
    container_name: manufacturer-mariadb
    restart: on-failure:5
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - ./manufacturer-mariadb.env
    mem_limit: 300m
    mem_reservation: 100m
    cpu_shares: 5
    pids_limit: 100
    networks:
      - manufacturer_network

networks:
  manufacturer_network:
    driver: bridge
    name: manufacturer_network
